"""Codes de raison NO_BET stables (docs/final_engine_specification.md
section 14). Chaque NO_BET doit porter au moins un de ces codes - jamais
une sortie silencieuse."""

from __future__ import annotations

INSUFFICIENT_HISTORY = "INSUFFICIENT_HISTORY"
AMBIGUOUS_COLLECTION_DAY = "AMBIGUOUS_COLLECTION_DAY"
MARKET_DATA_UNAVAILABLE = "MARKET_DATA_UNAVAILABLE"
DISTRIBUTION_INCONSISTENT = "DISTRIBUTION_INCONSISTENT"
INSUFFICIENT_CONFIDENCE_CALIBRATION_ZONE = "INSUFFICIENT_CONFIDENCE_CALIBRATION_ZONE"
DISCRIMINATION_NOT_DEMONSTRATED = "DISCRIMINATION_NOT_DEMONSTRATED"
EDGE_BELOW_THRESHOLD = "EDGE_BELOW_THRESHOLD"
UNCERTAINTY_TOO_HIGH = "UNCERTAINTY_TOO_HIGH"
MARKET_NOT_USABLE = "MARKET_NOT_USABLE"
OTHER_BLOCKING_CONDITION = "OTHER_BLOCKING_CONDITION"

ALL_CODES = frozenset(
    {
        INSUFFICIENT_HISTORY,
        AMBIGUOUS_COLLECTION_DAY,
        MARKET_DATA_UNAVAILABLE,
        DISTRIBUTION_INCONSISTENT,
        INSUFFICIENT_CONFIDENCE_CALIBRATION_ZONE,
        DISCRIMINATION_NOT_DEMONSTRATED,
        EDGE_BELOW_THRESHOLD,
        UNCERTAINTY_TOO_HIGH,
        MARKET_NOT_USABLE,
        OTHER_BLOCKING_CONDITION,
    }
)
